# Generated by Django 4.0.6 on 2022-07-11 05:48

from django.db import migrations, models
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_companytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ct',
            field=models.ForeignKey(default=mysite.models.get_defalut_ct, on_delete=django.db.models.deletion.CASCADE, to='mysite.companytype', verbose_name='類別'),
        ),
    ]
